version: '3.7'

services:
  devbaier:
    image: ghcr.io/{{username}}/devbaier.ch:latest
    container_name: devbaier.ch
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.devbaier.entrypoints=https
      - traefik.http.routers.devbaier.rule=Host(`devbaier.ch`)
      - traefik.http.routers.devbaier.tls=true
    deploy:
      update_config:
        order: start-first
    networks:
      - traefik    
networks:
 traefik:
  name: traefik_traefik