version: '3.9'

services:
  test:
    image: devbaier:latest
    container_name: devbaier.ch
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.devbaier.traefik_api.entrypoints=https
      - traefik.http.devbaier.traefik_api.rule=Host(`devbaier.ch`)
      - traefik.http.devbaier.traefik_api.service=devbaier
      - traefik.http.devbaier.traefik_api.tls=true
      - traefik.http.services.traefik_api.loadbalancer.server.port=3000
    networks:
      - traefik

networks:
  traefik:
    name: traefik_traefik